version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - cd client; npm install; cd ..

  build:
    commands:
      - make release

artifacts:
  files:
    - target/darkchess-1.0-SNAPSHOT.jar
    - client/build/**/*
    - appspec.yml
    - scripts/*

cache:
  paths:
    - '/root/.m2/**/*'
